/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.probestack.forgestudio.design.api;

import com.probestack.forgestudio.design.model.ErrorResponse;
import com.probestack.forgestudio.design.model.GeocodeResult;
import com.probestack.forgestudio.design.model.NormalisedAddress;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-14T07:15:01.769029535Z[GMT]")@Validated
@Tag(name = "Geocoding", description = "Convert between addresses and coordinates")
public interface GeocodingApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /geocode : Geocode an address
     * Returns latitude and longitude for a free-form address string. Results are cached for 24 hours.
     *
     * @param address Free-form address to geocode (required)
     * @param country ISO 3166-1 alpha-2 country hint (optional)
     * @return Address geocoded successfully (status code 200)
     *         or Invalid request payload or parameters. (status code 400)
     *         or Missing or invalid API Key. (status code 401)
     *         or Resource not found. (status code 404)
     *         or Internal server error. (status code 500)
     */
    @Operation(
        operationId = "geocodeAddress",
        summary = "Geocode an address",
        description = "Returns latitude and longitude for a free-form address string. Results are cached for 24 hours.",
        tags = { "Geocoding" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Address geocoded successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GeocodeResult.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request payload or parameters.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Missing or invalid API Key.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/geocode",
        produces = { "application/json" }
    )
    
    default ResponseEntity<GeocodeResult> geocodeAddress(
        @NotNull @Size(min = 3) @Parameter(name = "address", description = "Free-form address to geocode", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "address", required = true) String address,
        @Size(min = 2, max = 2) @Parameter(name = "country", description = "ISO 3166-1 alpha-2 country hint", in = ParameterIn.QUERY) @Valid @RequestParam(value = "country", required = false) String country
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "{ \"address\" : { \"country\" : \"US\", \"city\" : \"NEW YORK\", \"postalCode\" : \"10001-1234\", \"latitude\" : 40.750742, \"state\" : \"NY\", \"line2\" : \"APT 4B\", \"line1\" : \"123 MAIN ST\", \"longitude\" : -73.993439 }, \"matchQuality\" : \"ROOFTOP\", \"query\" : \"123 Main Street, New York\", \"latitude\" : 40.750742, \"longitude\" : -73.993439 }";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }


    /**
     * GET /reverse-geocode : Reverse geocode coordinates
     * Returns the nearest postal address for a latitude and longitude pair.
     *
     * @param lat  (required)
     * @param lon  (required)
     * @return Coordinates resolved successfully (status code 200)
     *         or Invalid request payload or parameters. (status code 400)
     *         or Missing or invalid API Key. (status code 401)
     *         or Resource not found. (status code 404)
     *         or Internal server error. (status code 500)
     */
    @Operation(
        operationId = "reverseGeocode",
        summary = "Reverse geocode coordinates",
        description = "Returns the nearest postal address for a latitude and longitude pair.",
        tags = { "Geocoding" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Coordinates resolved successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NormalisedAddress.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request payload or parameters.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Missing or invalid API Key.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/reverse-geocode",
        produces = { "application/json" }
    )
    
    default ResponseEntity<NormalisedAddress> reverseGeocode(
        @NotNull @DecimalMin("-90") @DecimalMax("90") @Parameter(name = "lat", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "lat", required = true) Double lat,
        @NotNull @DecimalMin("-180") @DecimalMax("180") @Parameter(name = "lon", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "lon", required = true) Double lon
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "{ \"country\" : \"US\", \"city\" : \"NEW YORK\", \"postalCode\" : \"10001-1234\", \"latitude\" : 40.750742, \"state\" : \"NY\", \"line2\" : \"APT 4B\", \"line1\" : \"123 MAIN ST\", \"longitude\" : -73.993439 }";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }

}
